language: python
python:
    - "3.5"
    - "2.7"

before_install:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url s2.testspace.com

install:
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  - pytest --junit-xml=testresults.xml

after_script:
  - testspace [$TRAVIS_PYTHON_VERSION]testresults*.xml