language: python
python:
    - "2.7"
    - "3.5"

before_install:
  - mkdir -p $HOME/bin
  - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url s2.testspace.com

install:
  - pip install tox
  - pip install --user codecov

script:
  - export PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR
  - tox -e py

after_script:
  - codecov
  - if [ "${TRAVIS_PYTHON_VERSION}" = "3.5" ]; then
      testspace [${TRAVIS_PYTHON_VERSION}]flake8.txt{lint} [${TRAVIS_PYTHON_VERSION}/tests]testresults.xml{tests} --link=codecov;
    else
      testspace [${TRAVIS_PYTHON_VERSION}/tests]testresults.xml{tests};
    fi